export { default as  HomeScreen} from './home'
export { default as  AccountScreen} from './account'
export { default as  SettingScreen} from './setting'
export { default as  LoginScreen} from './login'
export { default as  RegisterScreen} from './register'