export default {
    HOME_SCREEN: "HOME_SCREEN",
    SETTING_SCREEN: "SETTING_SCREEN",
    ACCOUNT_SCREEN: "ACCOUNT_SCREEN",
    LOGIN_SCREEN: "LOGIN_SCREEN",
    REGISTER_SCREEN: "REGISTER_SCREEN",

    MAIN:"MAIN"
}